name: Coppermind
description: Memoize buildkite steps based on treehashes
author: https://github.com/staticfloat
configuration:
  properties:
    inputs:
      type: array
    outputs:
      type: array
    s3_prefix:
      type: string
    s3_region:
      type: string
  additionalProperties: false
