name: Coppermind
description: Memoize buildkite steps based on treehashes
author: https://github.com/staticfloat
configuration:
  properties:
    # This array provides a list of glob patterns to consider as inputs to the memoization hashing
    inputs:
      type: array

    # Set this to something like `s3://bucket/prefix`
    s3_prefix:
      type: string

    # Give a name to the artifact that gets uploaded
    artifact_name:
      type: string
  additionalProperties: false
