#!/bin/bash

COPPERMIND_REPO="$( cd "$( dirname "$( dirname "${BASH_SOURCE[0]}" )" )" &> /dev/null && pwd )"
source "${COPPERMIND_REPO}/lib/common.sh"

# Skip uploading if we either skipped the command, or were given our artifacts from a previous step via `input_from`
if [[ "${BUILDKITE_PLUGIN_COPPERMIND_SKIP_COMMAND:-no}" == "yes" ]] || [[ -v "BUILDKITE_PLUGIN_COPPERMIND_INPUT_FROM" ]]; then
    echo "--- Skipping upload"
    exit 0
fi

# Upload each of our patterns, using buildkite-agent artifact to do so
echo "--- Uploading artifacts"
buildkite-agent artifact upload "$(join_by ";" "${OUTPUT_PATTERNS[@]}")" "s3://${S3_BUCKET}/${S3_PREFIX}/${BUILDKITE_PLUGIN_COPPERMIND_INPUT_HASH}"
