#!/bin/bash

COPPERMIND_REPO="$( cd "$( dirname "$( dirname "${BASH_SOURCE[0]}" )" )" &> /dev/null && pwd )"
source "${COPPERMIND_REPO}/lib/common.sh"

# Upload each of our patterns, using buildkite-agent artifact to do so
echo "--- Uploading artifacts"
buildkite-agent artifact upload "$(join_by ";" "${OUTPUT_PATTERNS[@]}")" "s3://${S3_BUCKET}/${S3_PREFIX}/${BUILDKITE_PLUGIN_COPPERMIND_INPUT_HASH}"
