#!/bin/bash

COPPERMIND_REPO="$( cd "$( dirname "$( dirname "${BASH_SOURCE[0]}" )" )" &> /dev/null && pwd )"
source "${COPPERMIND_REPO}/lib/common.sh"

# Start hashing up our input glob patterns
PATTERN_IDX=0
INPUT_TREEHASHES=()
while [[ -v "BUILDKITE_PLUGIN_COPPERMIND_INPUTS_${PATTERN_IDX}" ]]; do
    # Fetch the pattern
    PATTERN_VARNAME="BUILDKITE_PLUGIN_COPPERMIND_INPUTS_${PATTERN_IDX}"
    PATTERN="${!PATTERN_VARNAME}"

    # Calculate treehash
    TREEHASH="$(collect_glob_pattern "${PATTERN}" | calc_treehash)"
    echo "[${PATTERN}] treehash: ${TREEHASH}"
    INPUT_TREEHASHES+=( "${TREEHASH}" )

    PATTERN_IDX=$((${PATTERN_IDX} + 1))
done

# Hash all treehashes together to get full input hash
export BUILDKITE_PLUGIN_COPPERMIND_INPUT_HASH=$(printf "%s" "${INPUT_TREEHASHES[@]}" | calc_shasum)

# Get listing of all files that exist with the given prefix
S3_LISTING=$((AWS_ACCESS_KEY_ID=${BUILDKITE_S3_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${BUILDKITE_S3_SECRET_ACCESS_KEY} aws s3 ls --recursive "${S3_PREFIX}/${BUILDKITE_PLUGIN_COPPERMIND_INPUT_HASH}" || true) | awk '{ $1=$2=$3=""; print $0 }' | sed 's/^[ \t]*//')

if [[ -n "${S3_LISTING}" ]]; then
    echo "Found previously uploaded artifacts: ${S3_LISTING}"
    touch .buildkite_plugin_coppermind_skip_command
fi
