#!/bin/bash

COPPERMIND_REPO="$( cd "$( dirname "$( dirname "${BASH_SOURCE[0]}" )" )" &> /dev/null && pwd )"
source "${COPPERMIND_REPO}/lib/common.sh"

# Skip uploading if the pre-command says we've already done this
if [[ ${BUILDKITE_PLUGIN_COPPERMIND_SKIP_COMMAND:-no} == "yes"]]; then
    exit 0
fi

# Upload each of our patterns, using buildkite-agent artifact to do so
OUTPUT_PATTERNS=()
PATTERN_IDX=0
while [[ -v "BUILDKITE_PLUGIN_COPPERMIND_OUTPUTS_${PATTERN_IDX}_PATTERN" ]]; do
    # Fetch the pattern
    PATTERN_VARNAME="BUILDKITE_PLUGIN_COPPERMIND_OUTPUTS_${PATTERN_IDX}_PATTERN"
    OUTPUT_PATTERNS+=( "${!PATTERN_VARNAME}" )

    PATTERN_IDX=$((${PATTERN_IDX} + 1))
done

buildkite-agent artifact upload $(join_by ";" ${OUTPUT_PATTERNS[@]}) "${S3_PREFIX}"
